# Generated by Django 5.2.8 on 2025-11-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10),
        ),
    ]
